services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  fastapi-app:
    image: warehouse-fastapi-app:latest
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      TZ: Europe/Vienna
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mcp:
    image: warehouse-mcp:latest
    depends_on:
      fastapi-app:
        condition: service_healthy
    environment:
      API_BASE_URL: http://fastapi-app:8000
      PYTHONUNBUFFERED: "1"
      TZ: Europe/Vienna
    restart: "no"

  mesa-simulation:
    image: warehouse-mesa:latest
    depends_on:
      fastapi-app:
        condition: service_healthy
    environment:
      WAREHOUSE_URL: http://fastapi-app:8000
      PYTHONUNBUFFERED: "1"
      IN_DOCKER: "1"
      TZ: Europe/Vienna
      NUM_CUSTOMERS: "5"
      NUM_FULFILLMENT_AGENTS: "2"
      SOLARA_ASSETS_PROXY: "False"
      TINI_SUBREAPER: "1"
    ports:
      - "8521:8521"
    restart: unless-stopped
    command: ["/usr/bin/tini", "--", "python", "warehouse_simulation.py", "server"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8521/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    init: true
    stop_grace_period: 15s

  mesa-headless:
    image: warehouse-mesa:latest
    depends_on:
      fastapi-app:
        condition: service_healthy
    environment:
      WAREHOUSE_URL: http://fastapi-app:8000
      PYTHONUNBUFFERED: "1"
      IN_DOCKER: "1"
      TZ: Europe/Vienna
      NUM_CUSTOMERS: "10"
      NUM_FULFILLMENT_AGENTS: "3"
      MAX_STEPS: "1000"
      SOLARA_ASSETS_PROXY: "False"
      TINI_SUBREAPER: "1"
    command: ["/usr/bin/tini", "--", "python", "warehouse_simulation.py"]
    restart: "no"
    profiles:
      - headless
    init: true

volumes:
  redis_data:

networks:
  default:
    name: warehouse-network