services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  fastapi-app:
    image: warehouse-fastapi-app:latest
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "8000:8000"
    restart: unless-stopped

  mcp:
    image: warehouse-mcp:latest
    depends_on:
      - fastapi-app
    environment:
      API_BASE_URL: http://fastapi-app:8000
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped

volumes:
  redis_data: